### ISSUE TITLE
Translate into French

### ISSUE THREAD

**Issue by liuderchi** [liuderchi/atom-i18n#30]
files require translation:
  - [x] `def/fr/about.cson` #74
  - [x] `def/fr/context.cson` #74
  - [x] `def/fr/menu_darwin.cson` #74
  - [x] `def/fr/menu_linux.cson` #74
  - [x] `def/fr/menu_win32.cson` #74
  - [x] `def/fr/settings.cson` #74

for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by julienth37** [comment]
Hi,
I can take the translation. You could assign me this issue.

**Comment by liuderchi** [comment]
@julienth37 Thank you so much for taking this translation!
Looks like I cannot assign you in this issue page.

It's also welcome to create a Pull Request first.
If you come across any problems, feel free to leave comment here. :smile:

**Comment by preco21** [comment]
@Malivuk You maybe nterested? (my french friend)

**Comment by chezyann** [comment]
I may help too if you want ? :)

**Comment by liuderchi** [comment]
currently @julienth37 is assigned to this job.

@julienth37 would you like to have @chezyann join and split this issue into smaller ones?

**Comment by julienth37** [comment]
@chezyann you're welcome for help !

**Comment by chezyann** [comment]
@julienth37 Merci beaucoup / Thank you very much :-)

**Comment by chezyann** [comment]
@julienth37 What file do you want me to begin with ?

**Comment by julienth37** [comment]
@chezyann I didn't start yet so I let you pick the one you want !

**Comment by swirly** [comment]
Hello everybody. I would gladly translate also. Began to use atom with pupils, most of them having an awful english.

**Comment by chezyann** [comment]
Hi @swirly and thanks for your proposal !
I've already fully translated about.cson, context.cson, menu_darwin.cson, menu_linux.cson and menu_win32.cson. (and welcome.cson)
And I got a 30% translation of settings.cson.

However there might be some translation mistakes since I'm not using every Atom functions ; as a consequence it would be very great if you were OK to review my pull request when it will be done.

@liuderchi I tried to `git push -u origin chezyann_fr_translation` my 6/7 partial translation with no success :
```
error: src refspec chezyann_fr_translation does not match any.
error: failed to push some refs to 'https://github.com/liuderchi/atom-i18n.git'
```
What could be the correct way to do it ?

**Comment by liuderchi** [comment]
@chezyann it looks like you forgot to fork this repo.

Please follow [#Steps to Contribute](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md#steps-to-contribute).
  - NOTE: step no.2 of the guide: *fork* this repo means clicking button "fork" in [upper right ](https://help.github.com/articles/fork-a-repo/#fork-an-example-repository) so that you own a "copy" of this repo in order to grant access to push commits.

**Comment by chezyann** [comment]
@julienth37 and @swirly > Would you review my humble translation ?
[Right there](https://github.com/liuderchi/atom-i18n/pull/74)

**Comment by liuderchi** [comment]
Thank you @chezyann :100: 
Quick Tip: you can type `#ISSUE_NUMBER` to reference issue or pull request as shortcut.
