### ISSUE TITLE
New Options in Settings Tab for v1.15 are not translated (x7)

### ISSUE THREAD

**Issue by liuderchi** [liuderchi/atom-i18n#47]
New UI elements up to Atom v1.15 (currently beta) are added to *settings page*.

New i18n Items are added according to [this commit](https://github.com/liuderchi/atom-i18n/commit/6c876f934b830a3e3e84e8558891b97c78244af8):

`settings.cson`
  - `core.closeDeletedFileTabs` (x2)
  - `desc` of `core.restorePreviousWindowsOnStart` (x1)
  - `core.useProxySettingsWhenCallingApm` (x2)
  - `editor.showCursorOnSelection` (x2)

progress
- [x] `de/settings.cson` (#100)
- [x] `es/settings.cson` (#48)
- [x] `ja/settings.cson` (#113)
- [x] `ko/settings.cson` (#49)
- [x] `zh-cn/settings.cson` (#54)

**Comment by polynoman** [comment]
#47 and #100 seem to complete the issue, can it become closed?

**Comment by liuderchi** [comment]
@polynoman thanks for your hard work 🙏
Will close this after #100 is merged
